import { INodeOptionsValue, INodeParams } from '../../src';
export declare const nftOperation: INodeOptionsValue[];
export declare const getWalletNFTs: INodeParams[];
export declare const getNFTTransfersByBlock: INodeParams[];
export declare const getWalletNFTTransfers: INodeParams[];
export declare const getWalletNFTCollections: INodeParams[];
export declare const getNFTsForContract: INodeParams[];
export declare const getNFTTrades: INodeParams[];
export declare const getNFTLowestPrice: INodeParams[];
export declare const getContractNFTs: INodeParams[];
export declare const reSyncMetadata: INodeParams[];
export declare const getNFTTokenIdMetadata: INodeParams[];
export declare const getNFTTokenIdTransfers: INodeParams[];
